version: '3'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_net

networks:
  redis_net:
    driver: bridge

volumes:
  redis_data:

